# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/

# Setup
title:               Solo Player's Logbook
tagline:             - an online gaming journal by Finch204
description:         Solo Player's Logbook
url:                 
baseurl:             'https://finch204.github.io'
paginate:            5

# About/contact
author:
  name:              Finch204
  url:               
  email:             finch204@outlook.com

# Custom vars
version:             1.0.0
